### ISSUE TITLE
Link to Oracle dataset doesn't work

### ISSUE THREAD

**Issue by arghavanMor** [ameyaKetkar/RMinerEvaluationTools#1]
Hi,
Thank you for sharing the evaluation tool. I tried to download the oracle but all the links to the oracle are broken. Would you please repair the link or send me the oracle dataset?

**Comment by tsantalis** [comment]
Hi @arghavanMor 

The latest version of the oracle in json format is available at
https://github.com/tsantalis/RefactoringMiner/blob/master/src/test/resources/oracle/data.json

**Comment by tsantalis** [comment]
@arghavanMor 
To access the website of the oracle, the link is
http://refactoring.encs.concordia.ca/oracle/

But many browsers automatically force `https` in the URL.
You can find in the link below instructions on how to enforce `http` url in Chrome browser.
https://superuser.com/questions/565409/how-to-stop-an-automatic-redirect-from-http-to-https-in-chrome

**Comment by arghavanMor** [comment]
Thank you!
